# agents/QueryAgent.py

"""
The QueryAgent is a specialist agent responsible for interacting with the database.

Its sole purpose is to receive a specific, quantitative question, translate it
into a valid BigQuery SQL query, execute it using its single available tool,
and return the raw data result. It leverages the powerful self-correction
capabilities of the Gemini model to handle complex SQL generation and error recovery.
"""

from typing import Any, Dict
import json
import traceback

from google import genai
from google.genai.types import (
    Tool, FunctionDeclaration, Schema, Type, Content, Part, FunctionResponse, GenerateContentConfig
)

from agents.core import Agent
from tools.SQLTool import execute_sql_query
from utilities import PROMPTS, format_prompt
from dbconnectors import bqconnector

class QueryAgent(Agent):
    """
    An agent that specializes in answering questions by querying a SQL database.
    """
    agentType: str = "QueryAgent"

    def __init__(self, model_id: str = 'gemini-2.5-flash'):
        """
        Initializes the QueryAgent with a powerful model for SQL generation.
        """
        super().__init__()
        self.model_id = model_id
        # We set temperature to 0.0 to make SQL generation deterministic and reliable.
        self.generation_config = GenerateContentConfig(temperature=0.0)

    def run(self, dataframe, reference_query, question: str) -> Dict[str, Any]:
        """
        Executes the full tool-calling loop to answer a specific database question.

        Args:
            question: A clear, specific question that can be answered by the database.

        Returns:
            A dictionary containing the JSON result from the SQL query or an error message.
        """
        # 1. Define the agent's single tool: execute_sql_query.
        sql_function_declaration = FunctionDeclaration(
            name="execute_sql_query",
            description=(
                "Executes a BigQuery SQL query and returns the result as a JSON string. "
                "Use this tool to answer the user's question about quantitative data."
            ),
            parameters=Schema(
                type=Type.OBJECT,
                properties={
                    "sql_query": Schema(type=Type.STRING, description="A syntactically correct BigQuery SQL query string.")
                },
                required=["sql_query"],
            ),
        )
        sql_tool = Tool(function_declarations=[sql_function_declaration])
        # The tool config combines the tool definition with our generation parameters.
        tool_config = GenerateContentConfig(tools=[sql_tool], temperature=0.0)

        # 2. Prepare the prompt with detailed schema context.
        try:
            prompt_template = PROMPTS['query_agent_prompt']
        except KeyError:
            return {"error": "Could not find 'query_agent_prompt' in prompts.yaml."}

        initial_prompt = format_prompt(
            prompt_template,
            schema_context = bqconnector.get_schema_context(dataframe),
            reference_query = reference_query,
            question=question
        )

        # 3. Set up and run the tool-calling loop.
        conversation_history: list = [Content(parts=[Part(text=initial_prompt)], role="user")]
        print(f"    -> QueryAgent starting loop for question: \"{question}\"")
        for i in range(2): # Loop a few times to allow for self-correction. original was 5
            try:
                response = self.client.models.generate_content(
                    model=self.model_id,
                    contents=conversation_history,
                    config=tool_config,
                )
                
                # Extract token usage from the response
                self._extract_token_usage(response)

                # Check for results of query generated by Query Agent
                part = response.candidates[0].content.parts[0]
                if part.function_call:

                    if part.function_call.name == "execute_sql_query":
                        query_result = execute_sql_query(**part.function_call.args)
                        if len(query_result) == 2:
                            result, response_json = query_result
                        else:
                            result = query_result
                        if not 'error' in result:
                            print(f"    -> QueryAgent finished with a json response.")
                            try:
                                return json.loads(result), response_json
                            except json.JSONDecodeError:
                                # If it's not valid JSON, return it as a result string.
                                return {"result": part.text}

                response_candidate = response.candidates[0]
                
                # If the model returns text, it has finished its work for this turn.
                if response_candidate.content.parts[0].text:
                    print(f"    -> QueryAgent finished with a text response.")
                    # The agent's prompt instructs it to return raw JSON.
                    try:
                        return json.loads(response_candidate.content.parts[0].text)
                    except json.JSONDecodeError:
                        # If it's not valid JSON, return it as a result string.
                        return {"result": response_candidate.content.parts[0].text}

                # Otherwise, execute the requested tool call.
                function_call = response_candidate.content.parts[0].function_call
                tool_name = function_call.name
                tool_args = dict(function_call.args)

                print(f"      -> QueryAgent's model requested to call tool: '{tool_name}'")
                
                conversation_history.append(response_candidate.content)

                if tool_name == "execute_sql_query":
                    tool_result_str = execute_sql_query(**tool_args)

                    # THIS IS THE FIX: Handle the "no results" case explicitly.
                    # This prevents the agent from crashing and allows it to report gracefully.
                    if "Query executed successfully but returned no results" in tool_result_str:
                        print("    -> SQLTool reported no results. Finalizing turn with a clear message.")
                        return {"result": "No matching records were found in the database."}
                    
                    tool_result = tool_result_str
                else:
                    tool_result = f"Error: Unknown tool '{tool_name}'"

                tool_response_content = Content(
                    parts=[Part(function_response=FunctionResponse(name=tool_name, response={"result": tool_result}))],
                    role="user" 
                )
                conversation_history.append(tool_response_content)

            except Exception as e:
                print(f"    [!!!] An error occurred in the QueryAgent loop: {e}")
                traceback.print_exc()
                return {"error": f"An unexpected error occurred: {e}"}

        return {"error": "QueryAgent failed to produce a result after multiple turns."}
    
    def debug_sql(self, sql_query: str) -> str:
        query = sql_query
        response = self.client.models.generate_content(
                    model=self.model_id,
                    contents=f"Given the following sql query, {sql_query}, fix it and return the correct sql query and only the correct sql query"
                )
        query = response.candidates[0].content.parts[0].text
        return query